services:
 tracking_server:
    build:
      context: ..
      dockerfile: ./mlflow_deploy/dockerfile.mlflow
    image: mlflow_server
    container_name: mlflow_server_standalone
    ports:
      - "${MLFLOW_PORT}:5000"
    networks:
      minio_network:
        ipv4_address: 172.20.0.3
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY} #minio accesskey
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY} #minio secret accesskey
      - MLFLOW_S3_ENDPOINT_URL= http://172.20.0.2:${MINIO_PORT} #point to minio >> in the form of http://{ip}:{api port}
      - MLFLOW_S3_IGNORE_TLS=true
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --host 0.0.0.0
      --default-artifact-root s3://${MLFLOW_BUCKET_NAME}
#set backend uri >> some DB, set artifact to minio(s3) >> {ip}://{bucket name}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MLFLOW_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  minio_network:
    external: true