services:
  spark-master:
    image: bitnami/spark:3.4.3
    container_name: "spark-master"
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "${SPARK_MASTER_PORT}:7077"
      - "${SPARK_MASTER_UI_PORT}:8080"
    volumes:
      - ./src:/src
      - ./data:/data
      - ./output:/output

#   spark-worker-a:
#     image: bitnami/spark:3.4.3
#     ports:
#       - "9091:8080"
#       - "${SPARK_WORKER_A_PORT}:7000"
#     depends_on:
#       - spark-master
#     environment:
#       - SPARK_MASTER_URL=spark://spark-master:7077
#       - SPARK_WORKER_CORES=2
#       - SPARK_WORKER_MEMORY=1G
#       - SPARK_DRIVER_MEMORY=1G
#       - SPARK_EXECUTOR_MEMORY=1G
#       - SPARK_MODE=worker
#       - SPARK_LOCAL_IP=spark-worker-a
# #     - SPARK_USER=spark
#   spark-worker-b:
#     image: bitnami/spark:3.4.3
#     ports:
#       - "9092:8080"
#       - "${SPARK_WORKER_B_PORT}:7000"
#     depends_on:
#       - spark-master
#     environment:
#       - SPARK_MODE=worker
#       - SPARK_MASTER_URL=spark://spark-master:7077
#       - SPARK_WORKER_CORES=2
#       - SPARK_WORKER_MEMORY=1G
#       - SPARK_DRIVER_MEMORY=1G
#       - SPARK_EXECUTOR_MEMORY=1G
#       - SPARK_LOCAL_IP=