# Stage 1: Build stage with Python 3.8
FROM python:3.10.14-slim as build-stage

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Final stage with Spark and Python
FROM bitnami/spark:latest

WORKDIR  /app

COPY --from=build-stage /app /app

COPY app/ /opt/spark-job/

COPY deploy_kafka/run.sh /opt/bitnami/spark/

ENV PYSPARK_PYTHON=/usr/bin/python3.10.14