services:
 tracking_server:
    # build:
    #   context: .
    #   dockerfile: ./dockerfile.mlflow
    image: social-sentiment/mlflow:.
    container_name: social-sentiment-mlflow
    volumes:
      - ./mlruns:/mlruns
    ports:
      - "${MLFLOW_PORT}:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY} #minio accesskey
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY} #minio secret accesskey
      - MLFLOW_S3_ENDPOINT_URL= http://${SERVER_IP}:${MINIO_PORT} #point to minio >> in the form of http://{ip}:{api port}
      - MLFLOW_S3_IGNORE_TLS=true
    command: >
      mlflow server
      --backend-store-uri file:///mlruns
      --host 0.0.0.0
      --default-artifact-root s3://${MLFLOW_BUCKET_NAME}
#set backend uri >> some DB, set artifact to s3 >> {ip}://{bucket name}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${SERVER_IP}:${MLFLOW_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3