services:
  s3:
    restart: always
    image: social-sentiment/minio:1.0.0
    container_name: social-sentiment-minio
    volumes:
      - ./minio_data:/data
    ports:
      - "${MINIO_PORT}:29000"
      - "${MINIO_CONSOLE_PORT}:29001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ADDRESS=${MINIO_ADDRESS} #same port number as api
      - MINIO_CONSOLE_ADDRESS=${MINIO_CONSOLE_ADDRESS} #same port number as console
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_STORAGE_USE_HTTPS=${MINIO_STORAGE_USE_HTTPS} #True or false
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${SERVER_IP}:${MINIO_PORT}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
