
services:
  s3:
    restart: always
    image: minio/minio:RELEASE.2024-07-04T14-25-45Z
    container_name: minio_standalone
    volumes:
      - minio_data:/data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    networks:
      - minio_network
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ADDRESS=${MINIO_ADDRESS} #same port number as api
      - MINIO_CONSOLE_ADDRESS=${MINIO_CONSOLE_ADDRESS} #same port number as console
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_STORAGE_USE_HTTPS=${MINIO_STORAGE_USE_HTTPS} #True or false
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${SERVER}:${MINIO_PORT}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:

networks:
  minio_network:
    external: true